//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoLesports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Csapat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Csapat()
        {
            this.Jatekos = new HashSet<Jatekos>();
        }
    
        public string Csapatnev { get; set; }
        public string Liga_nev { get; set; }
        public string Csapat_rovidites { get; set; }
        public string Org_szekhely { get; set; }
        public Nullable<System.DateTime> Alapitas_datum { get; set; }
        public string Fo_edzo { get; set; }
        public bool Bajnoksag_reszvetel { get; set; }
    
        public virtual Liga Liga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jatekos> Jatekos { get; set; }
    }
}
