//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoLesports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jatekos
    {
        public string Felhasznalonev { get; set; }
        public string Vezeteknev { get; set; }
        public string Keresztnev { get; set; }
        public Nullable<int> Eletkor { get; set; }
        public string Pozicio { get; set; }
        public string Nemzetiseg { get; set; }
        public string Csapatnev { get; set; }
    
        public virtual Csapat Csapat { get; set; }
    }
}
