//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoLesports.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoLesportsDBEntities1 : DbContext
    {
        public LoLesportsDBEntities1()
            : base("name=LoLesportsDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Csapat> Csapat { get; set; }
        public virtual DbSet<Jatekos> Jatekos { get; set; }
        public virtual DbSet<Liga> Liga { get; set; }
    }
}
